CC = gcc


getchr.o: getchr.c
ungetchr.o: ungetchr.c
get_test.o: getchr.c ungetchr.c get_test.c


#get_test_exe: get_test.o getchr.o ungetchr.o

#Makefile
#_getchr.h
#get_test.c
#getchr.c
#getchr.h
#ungetchr.c

